# Generated by Django 6.0.6 on 2026-06-29 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0002_remove_admin_group_adminserver_group_and_more'),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punishment_type', models.CharField(choices=[('ban', 'Бан'), ('mute', 'Мут'), ('gag', 'Гаг')], max_length=8)),
                ('target_steam_id', models.CharField(max_length=64)),
                ('target_name', models.CharField(max_length=64)),
                ('reason', models.TextField()),
                ('duration', models.IntegerField(help_text='Длительность в минутах (0 = перманент)')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('unban_reason', models.TextField(blank=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punishments_issued', to='admins.admin')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punishments', to='servers.server')),
                ('unbanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punishments_removed', to='admins.admin')),
            ],
            options={
                'verbose_name': 'Punishment',
                'verbose_name_plural': 'Punishments',
                'ordering': ['-issued_at'],
            },
        ),
    ]
