# Generated by Django 6.0.6 on 2026-06-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punishments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='punishment',
            name='ban_subnet',
            field=models.BooleanField(default=False, help_text='Банить всю подсеть /24 (например, 95.123.45.*)'),
        ),
        migrations.AddField(
            model_name='punishment',
            name='target_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP адрес игрока', null=True),
        ),
    ]
