# Generated by Django 6.0.6 on 2026-06-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punishments', '0002_punishment_ban_subnet_punishment_target_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punishment',
            name='ban_subnet',
            field=models.BooleanField(default=False, help_text='Банить всю подсеть'),
        ),
    ]
