# Generated by Django 6.0.6 on 2026-06-09 22:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=27015)),
                ('rcon_password', models.CharField(max_length=128)),
                ('game_type', models.CharField(choices=[('cs16', 'Counter-Strike 1.6'), ('cs2', 'Counter-Strike 2')], default='cs16', max_length=8)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
            },
        ),
    ]
