# Generated by Django 6.0.6 on 2026-06-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Верифицирован через API плагина'),
        ),
    ]
