# Generated by Django 6.0.6 on 2026-06-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_server_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='rcon_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
