# Generated by Django 6.0.6 on 2026-06-29 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='group',
        ),
        migrations.AddField(
            model_name='adminserver',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server_assignments', to='admins.admingroup'),
        ),
        migrations.AlterField(
            model_name='adminserver',
            name='flags',
            field=models.CharField(blank=True, default='', help_text='Индивидуальные флаги (если не используется группа)', max_length=32),
        ),
        migrations.AlterField(
            model_name='adminserver',
            name='immunity',
            field=models.IntegerField(default=0, help_text='Индивидуальный иммунитет (если не используется группа)'),
        ),
    ]
