# Generated by Django 6.0.6 on 2026-07-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_remove_admin_group_adminserver_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminserver',
            name='duration',
            field=models.IntegerField(default=0, help_text='Длительность прав в минутах (0 = навсегда)'),
        ),
        migrations.AddField(
            model_name='adminserver',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Дата истечения прав (вычисляется автоматически)', null=True),
        ),
    ]
