# Generated by Django 6.0.6 on 2026-07-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_adminserver_duration_adminserver_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminserver',
            name='duration',
            field=models.IntegerField(blank=True, default=0, help_text='Длительность прав в минутах (0 = навсегда)'),
        ),
        migrations.AlterField(
            model_name='adminserver',
            name='immunity',
            field=models.IntegerField(blank=True, default=0, help_text='Индивидуальный иммунитет (если не используется группа)', null=True),
        ),
    ]
